/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_wooy_proxy_jni_Kcp */

#ifndef _Included_me_wooy_proxy_jni_Kcp
#define _Included_me_wooy_proxy_jni_Kcp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_wooy_proxy_jni_Kcp
 * Method:    init
 * Signature: (Ljava/lang/String;ILjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_me_wooy_proxy_jni_Kcp_init
        (JNIEnv *, jobject, jstring, jint, jint, jstring, jint);


/*
 * Class:     me_wooy_proxy_jni_Kcp
 * Method:    sendBuf
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_me_wooy_proxy_jni_Kcp_sendBuf
        (JNIEnv *, jobject, jlong, jbyteArray,jint);

#ifdef __cplusplus
}
#endif
#endif
